name: Sync with Parent Repository

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Parent Repo as Upstream
        run: |
          git remote add upstream https://github.com/microsoft/autogen.git
          git fetch upstream main

      - name: Attempt Merge
        id: merge
        run: |
          git checkout main
          git merge --no-edit upstream/main || { echo "Merge conflict! Please resolve manually."; exit 1; }
          git push origin main
